### ISSUE TITLE
great pruning can we upgrade this for fastai2

### ISSUE THREAD

**Issue by gauravbrills** [crcrpar/fastai-optuna-rossman#3]
great pruning with Optuna can we upgrade this for fastai2, as some hyperparams are depreacted now .

**Comment by crcrpar** [comment]
Hi @gauravbrills thank you for your interest.

This repository was created mainly for https://medium.com/@crcrpar/optuna-fastai-tabular-model-001-55777031e288, and I haven't updated ever.

But I think we can do that and Optuna has supported fastai v2 https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.FastAIPruningCallback.html#optuna.integration.FastAIPruningCallback

Details can be wrong as I'm no longer Optuna maintainer

**Comment by gauravbrills** [comment]
Thanks
